-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

drop database bd_petshop;
create database bd_petshop;
use bd_petshop;


CREATE TABLE ENDERECO_CLIENTE (
ID_ENDERECO_CLIENTE INT(5) auto_increment PRIMARY KEY,
BAIRRO VARCHAR(250),
CEP CHAR(8),
COMPLEMENTO VARCHAR(50),
LOGADOURO VARCHAR(250),
NUMERO INT(6),
UF VARCHAR(2),
CIDADE VARCHAR(250),
FK_CLI_END INT(4)
);

CREATE TABLE PET (
ID_PET INT(5) auto_increment PRIMARY KEY,
NOME_PET VARCHAR(200),
DATA_CADASTRO DATE,
PET VARCHAR(50),
COR VARCHAR(250),
RACA VARCHAR(50),
PESO VARCHAR(4),
SEXO CHAR(2),
DATA_NASCIMENTO_PET DATE,
FK_PET_CLI INT(4)
);

CREATE TABLE HISTORICO (
ID_HISTORICO INT(5) auto_increment PRIMARY KEY,
SERVIÇO VARCHAR(50),
DATA_HISTORICO DATE,
HORARIO TIME,
FK_SERV_HIST INT(4)
);

CREATE TABLE ENDERECO_AMIGOS (
ID_END_AMG INT(5) auto_increment PRIMARY KEY,
BAIRRO VARCHAR(250),
CEP CHAR(8),
NUMERO INT(6),
UF CHAR(2),
CIDADE VARCHAR(200),
FK_AMG_END INT(4)
);

CREATE TABLE LOGIN_CLIENTE (
ID_LOGIN_CLIENTE INT(5) auto_increment PRIMARY KEY,
USERNAME VARCHAR(250),
SENHA VARCHAR(100),
DATA_DE_ENTRADA DATETIME,
DATA_DE_SAIDA DATETIME,
FK_CLI_LOG INT(4)
);

CREATE TABLE LOGIN_ADM (
ID_LOGIN INT(5) auto_increment PRIMARY KEY,
SENHA VARCHAR(100),
USERNAME VARCHAR(50),
FK_LOGIN INT(4)
);

CREATE TABLE ADM (
ID_ADM INT(5) auto_increment PRIMARY KEY,
NOME VARCHAR(50),
SOBRENOME VARCHAR(100)
);

CREATE TABLE AMIGOS_REC (
ID_AMG_REC INT(5) auto_increment PRIMARY KEY,
NOME VARCHAR(50),
SOBRENOME VARCHAR(50),
FK_AMG_SER INT(4)
);

CREATE TABLE ENDERECO_FUNCIONARIO (
ID_ENDERECO_FUNCIONARIO INT(5) auto_increment PRIMARY KEY,
BAIRRO VARCHAR(250),
CEP CHAR(8),
COMPLEMENTO VARCHAR(250),
LOGADOURO VARCHAR(250),
NUMERO VARCHAR(200),
UF CHAR(2),
CIDADE VARCHAR(200),
FK_FUN_END INT(4)
);

CREATE TABLE LOGIN_FUNCIONARIO (
ID_LOGIN_FUNCIONARIO INT(5) auto_increment PRIMARY KEY,
USERNAME VARCHAR(250),
SENHA VARCHAR(100),
DATA_DE_ENTRADA DATETIME,
DATA_DE_SAIDA DATETIME,
FK_FUN_LOG INT(4)
);

CREATE TABLE FUNCIONARIO (
ID_FUNCIONARIO INT(5) auto_increment PRIMARY KEY,
SOBRENOME VARCHAR(250),
NOME VARCHAR(50),
CPF CHAR(11),
DDD CHAR(2),
TELEFONE CHAR(9),
EMAIL VARCHAR(250),
DATA_NASCIMENTO DATE,
PROFISSAO VARCHAR(50),
DATA_ENTRADA DATETIME,
DATA_SAIDA DATETIME
);

CREATE TABLE CLIENTE (
ID_CLIENTE INT(5) auto_increment PRIMARY KEY,
NOME VARCHAR(100),
SOBRENOME VARCHAR(100),
CPF CHAR(11),
DDD CHAR(2),
TELEFONE CHAR(9),
DATA_NASCIMENTO DATE,
EMAIL VARCHAR(250),
DATA_ENTRADA DATETIME,
DATA_SAIDA DATETIME
);

CREATE TABLE SERVICOS (
ID_AGED_CLST INT(5) auto_increment  PRIMARY KEY,
SERVIÇO VARCHAR(50),
DATA_SERVICOS DATE,
HORARIO TIME,
FK_PET_AGE INT(4),
FOREIGN KEY(FK_PET_AGE) REFERENCES PET (ID_PET)
);

CREATE TABLE HISTORICO_FUN (
ID_HIST_FUN INT(5) auto_increment PRIMARY KEY,
DATA_ENTR DATETIME,
DATA_SAIDA DATETIME,
FK_FUN_HSIT INT(4),
FOREIGN KEY(FK_FUN_HSIT) REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
);

CREATE TABLE HISTORICO_CLI (
ID_HIST_CLI INT(5) auto_increment PRIMARY KEY,
DATA_ENTR DATETIME,
DATA_SAIDA DATETIME,
FK_CLI_HSIT INT(4),
FOREIGN KEY(FK_CLI_HSIT) REFERENCES CLIENTE (ID_CLIENTE)
);

ALTER TABLE ENDERECO_CLIENTE ADD FOREIGN KEY(FK_CLI_END) REFERENCES CLIENTE (ID_CLIENTE);
ALTER TABLE PET ADD FOREIGN KEY(FK_PET_CLI) REFERENCES CLIENTE (ID_CLIENTE);
ALTER TABLE HISTORICO ADD FOREIGN KEY(FK_SERV_HIST) REFERENCES SERVICOS (ID_AGED_CLST);
ALTER TABLE ENDERECO_AMIGOS ADD FOREIGN KEY(FK_AMG_END) REFERENCES AMIGOS_REC (ID_AMG_REC);
ALTER TABLE LOGIN_CLIENTE ADD FOREIGN KEY(FK_CLI_LOG) REFERENCES CLIENTE (ID_CLIENTE);
ALTER TABLE LOGIN_ADM ADD FOREIGN KEY(FK_LOGIN) REFERENCES ADM (ID_ADM);
ALTER TABLE AMIGOS_REC ADD FOREIGN KEY(FK_AMG_SER) REFERENCES SERVICOS (ID_AGED_CLST);
ALTER TABLE ENDERECO_FUNCIONARIO ADD FOREIGN KEY(FK_FUN_END) REFERENCES FUNCIONARIO (ID_FUNCIONARIO);
ALTER TABLE LOGIN_FUNCIONARIO ADD FOREIGN KEY(FK_FUN_LOG) REFERENCES FUNCIONARIO (ID_FUNCIONARIO);
